# Generated by Django 3.1 on 2020-08-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='session_end',
            field=models.DateField(verbose_name='Session end'),
        ),
    ]
